sudo: required
dist: trusty
language: node_js
node_js:
- '6'
cache:
  bundler: true
  directories:
  - ngx-interview-web/node_modules
  - "$(npm config get prefix)"
addons:
  apt:
    sources:
    - google-chrome
    packages:
    - google-chrome-stable
    - google-chrome-beta
before_install:
- export CHROME_BIN=chromium-browser
- export DISPLAY=:99.0
- sh -e /etc/init.d/xvfb start
before_script:
- cd ngx-interview-web
- npm install
- npm install -g karma
- npm run pree2e
- npm run ng lint
- npm run ng build --prod
- bash 404.sh
- npm test
- npm run http-server &
- sleep 1
script: npm run e2e
